// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIKsHfZ7xLHbYnpszUdbGPbsSTz82IO5o',
    appId: '1:1027923032857:web:761d8521a2549eeed46388',
    messagingSenderId: '1027923032857',
    projectId: 'smarthome-vize-30120104',
    authDomain: 'smarthome-vize-30120104.firebaseapp.com',
    storageBucket: 'smarthome-vize-30120104.appspot.com',
    measurementId: 'G-KXCBZ2X83E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaocwafLmSVUQYIGgm5RyPN8cW4xftPZA',
    appId: '1:1027923032857:android:b0899e572a490df3d46388',
    messagingSenderId: '1027923032857',
    projectId: 'smarthome-vize-30120104',
    storageBucket: 'smarthome-vize-30120104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPdNRjsY7v5uCw0jQ9apPAb4FwxMm4Hn4',
    appId: '1:1027923032857:ios:c7aaf1502ece10ead46388',
    messagingSenderId: '1027923032857',
    projectId: 'smarthome-vize-30120104',
    storageBucket: 'smarthome-vize-30120104.appspot.com',
    iosClientId: '1027923032857-256nkh7sfjm6j03euiinhoehnpni8d9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPdNRjsY7v5uCw0jQ9apPAb4FwxMm4Hn4',
    appId: '1:1027923032857:ios:c7aaf1502ece10ead46388',
    messagingSenderId: '1027923032857',
    projectId: 'smarthome-vize-30120104',
    storageBucket: 'smarthome-vize-30120104.appspot.com',
    iosClientId: '1027923032857-256nkh7sfjm6j03euiinhoehnpni8d9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
